import { AddIcon, Search2Icon } from "@chakra-ui/icons";
import {
  Box,
  Button,
  Center,
  Container,
  Input,
  InputGroup,
  InputLeftElement,
  SimpleGrid,
} from "@chakra-ui/react";
import { motion } from "framer-motion";
import Head from "next/head";
import { useEffect, useState } from "react";
import { CardNote } from "../Components/CardNote";
import { CreateNoteModal } from "../Components/CreateNoteModal";
import Nav from "../Components/Navbar";

const Home = () => {
  const [notes, setNotes] = useState<Array<any>>([]);
  const [modalOpen, setModalOpen] = useState(false);
  const [search, setSearch] = useState("");
  const [changeNote, setChangeNote] = useState(false);
  const [filterNotes, setFilterNotes] = useState<Array<any>>([]);

  useEffect(() => {
    let notesLocal: any = localStorage.getItem("notes");
    setNotes(JSON.parse(notesLocal));
  }, [modalOpen, changeNote]);

  const filter = () => {
    if (search) {
      setFilterNotes(
        notes.filter((item) =>
          String(item.title).toLowerCase().startsWith(search.toLowerCase())
        )
      );
    }else{
      setFilterNotes([])
    }
  };

  useEffect(() => {
    filter();
  }, [search]);

  return (
    <div>
      <Head>
        <title>Notes Day</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Container maxW={"container.xl"} mt={10} mb={10}>
        <CreateNoteModal open={modalOpen} setOpen={setModalOpen} />
        <Center justifyContent={"space-between"} gap={5}>
          <Box>
            <Button
              rightIcon={<AddIcon />}
              onClick={() => setModalOpen(!modalOpen)}
            >
              Nova Nota
            </Button>
          </Box>
          <Box>
            <InputGroup>
              <InputLeftElement
                pointerEvents="none"
                children={<Search2Icon />}
              />
              <Input
                onChange={(e) => setSearch(e.target.value)}
                placeholder="Procure por Notas"
              />
            </InputGroup>
          </Box>
        </Center>
        {filterNotes.length > 0 ? (
          <SimpleGrid columns={{ base: 1, md: 2, lg: 4 }} spacing={5} mt={10}>
            {filterNotes?.map((note, i) => (
              <motion.div
                initial={{ opacity: 0, y: "2vw" }}
                animate={{ opacity: 1, y: "0px" }}
                transition={{ type: "spring", duration: 1, bounce: 0 }}
              >
                <Box key={i}>
                  <CardNote
                    note={note}
                    notes={notes}
                    changeNote={changeNote}
                    setChangeNote={setChangeNote}
                  />
                </Box>
              </motion.div>
            ))}
          </SimpleGrid>
        ) : (
          <SimpleGrid columns={{ base: 1, md: 2, lg: 4 }} spacing={5} mt={10}>
            {notes?.map((note, i) => (
              <motion.div
                initial={{ opacity: 0, y: "2vw" }}
                animate={{ opacity: 1, y: "0px" }}
                transition={{ type: "spring", duration: 1, bounce: 0 }}
              >
                <Box key={i}>
                  <CardNote
                    note={note}
                    notes={notes}
                    changeNote={changeNote}
                    setChangeNote={setChangeNote}
                  />
                </Box>
              </motion.div>
            ))}
          </SimpleGrid>
        )}
      </Container>
    </div>
  );
};

export default Home;
